/**
 * Auto-generated by openapi-typescript. DO NOT EDIT.
 * Run `npm run api:generate` to regenerate from the API's OpenAPI spec.
 *
 * This is a placeholder — it will be replaced once the API is running
 * and `npm run api:generate` is executed.
 */

export interface paths {
  '/system/status': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': {
              application: string;
              status: string;
              timestamp: string;
            };
          };
        };
      };
    };
  };
}

export interface components {
  schemas: Record<string, never>;
}
